// Centralized permission resource & action enums
// Generated by scanning route requirePermission usages.

export enum PermissionResource {
  PRODUCTS = 'products',
  CATEGORIES = 'categories',
  SUBCATEGORIES = 'subcategories',
  ATTRIBUTES = 'attributes',
  INVENTORY = 'inventory',
  ORDERS = 'orders',
  USERS = 'users',
  ROLES = 'roles',
  SALES = 'sales',
  COUPONS = 'coupons',
  REVIEWS = 'reviews',
  CAMPAIGNS = 'campaigns',
  BANNERS = 'banners',
  GALLERY = 'gallery',
  ANALYTICS = 'analytics',
  INVOICES = 'invoices',
  LOGISTICS = 'logistics',
  TRANSACTIONS = 'transactions',
}

export enum PermissionAction {
  CREATE = 'create',
  READ = 'read',
  UPDATE = 'update',
  DELETE = 'delete',
  ALL = 'all',
  WILDCARD = '*',
}

// Typed permission tuple
export interface RolePermission {
  resource: PermissionResource;
  actions: PermissionAction[]; // actions granted on that resource
}

// Utility constant lists for validation or iteration
export const PERMISSION_RESOURCES: PermissionResource[] = Object.values(PermissionResource);
export const PERMISSION_ACTIONS: PermissionAction[] = Object.values(PermissionAction);
