import type { NextFunction, Request, Response } from 'express';
import { checkSchema, validationResult } from 'express-validator';

const MODEL_STATUSES = ['In-Warehouse', 'Shipped', 'Dispatched', 'Delivered', 'Returned', 'Failed'] as const;

const createShipmentValidator = (req: Request, res: Response, next: NextFunction) => {
  checkSchema({
    orderId: {
      in: ['body'],
      isMongoId: true,
      errorMessage: 'Order ID must be a valid MongoDB ID',
    },
    // trackingNumber is generated by the service; allow optional input but do not require
    trackingNumber: {
      in: ['body'],
      isString: true,
      optional: true,
      errorMessage: 'Tracking number should be a string',
    },
    courier: {
      in: ['body'],
      isString: true,
      notEmpty: true,
      errorMessage: 'Courier is required and should be a string',
    },
    shippingAddress: {
      in: ['body'],
      isObject: true,
      errorMessage: 'Shipping address must be an object',
    },
    'shippingAddress.firstName': {
      in: ['body'],
      isString: true,
      notEmpty: true,
      errorMessage: 'First name is required',
    },
    'shippingAddress.lastName': {
      in: ['body'],
      isString: true,
      notEmpty: true,
      errorMessage: 'Last name is required',
    },
    'shippingAddress.phoneNumber': {
      in: ['body'],
      isString: true,
      notEmpty: true,
      errorMessage: 'Phone number is required',
    },
    'shippingAddress.address1': {
      in: ['body'],
      isString: true,
      notEmpty: true,
      errorMessage: 'Address line 1 is required',
    },
    'shippingAddress.address2': {
      in: ['body'],
      isString: true,
      optional: true,
      errorMessage: 'Address line 2 should be a string',
    },
    'shippingAddress.city': {
      in: ['body'],
      isString: true,
      notEmpty: true,
      errorMessage: 'City is required',
    },
    'shippingAddress.state': {
      in: ['body'],
      isString: true,
      notEmpty: true,
      errorMessage: 'State is required',
    },
    'shippingAddress.zipCode': {
      in: ['body'],
      isString: true,
      notEmpty: true,
      errorMessage: 'Zip code is required',
    },
    'shippingAddress.country': {
      in: ['body'],
      isString: true,
      notEmpty: true,
      errorMessage: 'Country is required',
    },
    estimatedDelivery: {
      in: ['body'],
      isISO8601: true,
      optional: true,
      errorMessage: 'Estimated delivery must be a valid ISO 8601 date',
    },
    status: {
      in: ['body'],
      isString: true,
      optional: true,
      isIn: {
        options: [Array.from(MODEL_STATUSES)],
        errorMessage: 'Status must be one of: In-Warehouse, Shipped, Dispatched, Delivered, Returned, Failed',
      },
    },
    dimensions: {
      in: ['body'],
      optional: true,
      isObject: true,
      errorMessage: 'Dimensions must be an object',
    },
    'dimensions.length': { in: ['body'], optional: true, isFloat: true, errorMessage: 'length must be a number' },
    'dimensions.width': { in: ['body'], optional: true, isFloat: true, errorMessage: 'width must be a number' },
    'dimensions.height': { in: ['body'], optional: true, isFloat: true, errorMessage: 'height must be a number' },
    'dimensions.weight': { in: ['body'], optional: true, isFloat: true, errorMessage: 'weight must be a number' },
    cost: {
      in: ['body'],
      isFloat: true,
      notEmpty: true,
      errorMessage: 'cost is required and must be a number',
    },
    notes: { in: ['body'], optional: true, isString: true },
  });
  const errors = validationResult(req);
  if (!errors.isEmpty()) {
    return res.status(400).json({ errors: errors.array() });
  }
  next();
};

const updateShipmentValidator = (req: Request, res: Response, next: NextFunction) => {
  checkSchema({
    shipmentId: {
      in: ['params'],
      isMongoId: true,
      errorMessage: 'Shipment ID must be a valid MongoDB ID',
    },
    trackingNumber: {
      in: ['body'],
      isString: true,
      optional: true,
      errorMessage: 'Tracking number should be a string',
    },
    courier: {
      in: ['body'],
      isString: true,
      optional: true,
      errorMessage: 'Courier should be a string',
    },
    shippingAddress: {
      in: ['body'],
      isObject: true,
      optional: true,
      errorMessage: 'Shipping address must be an object',
    },
    estimatedDelivery: {
      in: ['body'],
      isISO8601: true,
      optional: true,
      errorMessage: 'Estimated delivery must be a valid ISO 8601 date',
    },
    status: {
      in: ['body'],
      isString: true,
      optional: true,
      isIn: {
        options: [Array.from(MODEL_STATUSES)],
        errorMessage: 'Status must be one of: In-Warehouse, Shipped, Dispatched, Delivered, Returned, Failed',
      },
    },
    dimensions: { in: ['body'], optional: true, isObject: true },
    'dimensions.length': { in: ['body'], optional: true, isFloat: true },
    'dimensions.width': { in: ['body'], optional: true, isFloat: true },
    'dimensions.height': { in: ['body'], optional: true, isFloat: true },
    'dimensions.weight': { in: ['body'], optional: true, isFloat: true },
    cost: { in: ['body'], optional: true, isFloat: true },
    notes: { in: ['body'], optional: true, isString: true },
  });
  const errors = validationResult(req);
  if (!errors.isEmpty()) {
    return res.status(400).json({ errors: errors.array() });
  }
  next();
};

const shipmentIdValidator = (req: Request, res: Response, next: NextFunction) => {
  checkSchema({
    shipmentId: {
      in: ['params'],
      isMongoId: true,
      errorMessage: 'Shipment ID must be a valid MongoDB ID',
    },
  });
  const errors = validationResult(req);
  if (!errors.isEmpty()) {
    return res.status(400).json({ errors: errors.array() });
  }
  next();
};

const updateStatusValidator = (req: Request, res: Response, next: NextFunction) => {
  checkSchema({
    shipmentId: {
      in: ['params'],
      isMongoId: true,
      errorMessage: 'Shipment ID must be a valid MongoDB ID',
    },
    status: {
      in: ['body'],
      isString: true,
      notEmpty: true,
      isIn: {
        options: [Array.from(MODEL_STATUSES)],
        errorMessage: 'Status must be one of: In-Warehouse, Shipped, Dispatched, Delivered, Returned, Failed',
      },
    },
    note: { in: ['body'], optional: true, isString: true },
  });
  const errors = validationResult(req);
  if (!errors.isEmpty()) {
    return res.status(400).json({ errors: errors.array() });
  }
  next();
};

const addTrackingValidator = (req: Request, res: Response, next: NextFunction) => {
  checkSchema({
    shipmentId: {
      in: ['params'],
      isMongoId: true,
      errorMessage: 'Shipment ID must be a valid MongoDB ID',
    },
    status: {
      in: ['body'],
      isString: true,
      notEmpty: true,
      isIn: {
        options: [Array.from(MODEL_STATUSES)],
        errorMessage: 'Status must be one of: In-Warehouse, Shipped, Dispatched, Delivered, Returned, Failed',
      },
    },
    location: {
      in: ['body'],
      isString: true,
      notEmpty: true,
      errorMessage: 'Location is required and should be a string',
    },
    description: {
      in: ['body'],
      isString: true,
      notEmpty: true,
      errorMessage: 'Description is required and should be a string',
    },
    timestamp: {
      in: ['body'],
      isISO8601: true,
      optional: true,
      errorMessage: 'Timestamp must be a valid ISO 8601 date',
    },
  });
  const errors = validationResult(req);
  if (!errors.isEmpty()) {
    return res.status(400).json({ errors: errors.array() });
  }
  next();
};

const statusFilterValidator = (req: Request, res: Response, next: NextFunction) => {
  checkSchema({
    status: {
      in: ['params'],
      isString: true,
      notEmpty: true,
      isIn: {
        options: [Array.from(MODEL_STATUSES)],
        errorMessage: 'Status must be one of: In-Warehouse, Shipped, Dispatched, Delivered, Returned, Failed',
      },
    },
  });
  const errors = validationResult(req);
  if (!errors.isEmpty()) {
    return res.status(400).json({ errors: errors.array() });
  }
  next();
};

const bulkUpdateValidator = (req: Request, res: Response, next: NextFunction) => {
  checkSchema({
    shipmentIds: {
      in: ['body'],
      isArray: {
        options: { min: 1 },
        errorMessage: 'shipmentIds must be an array with at least one ID',
      },
    },
    'shipmentIds.*': {
      in: ['body'],
      isMongoId: true,
      errorMessage: 'Each shipment ID must be a valid MongoDB ID',
    },
    status: {
      in: ['body'],
      isString: true,
      notEmpty: true,
      isIn: {
        options: [Array.from(MODEL_STATUSES)],
        errorMessage: 'Status must be one of: In-Warehouse, Shipped, Dispatched, Delivered, Returned, Failed',
      },
    },
    note: { in: ['body'], optional: true, isString: true },
  });
  const errors = validationResult(req);
  if (!errors.isEmpty()) {
    return res.status(400).json({ errors: errors.array() });
  }
  next();
};

const ShipmentValidator = {
  createShipmentValidator,
  updateShipmentValidator,
  shipmentIdValidator,
  updateStatusValidator,
  addTrackingValidator,
  statusFilterValidator,
  bulkUpdateValidator,
};

export default ShipmentValidator;
